### PR TITLE
Feature: tab selection view

### PR DESCRIPTION
**Pull request by fespinoza**
Screenshot 2021-08-30 at 10 11 34

### CODE REVIEW

**Review by kentrh — COMMENTED** [review]
Looking good! 

I guess this may be just a demo issue, but colors are wrong in demo app in dark mode. 

Simulator Screen Shot - iPhone 12 Pro - 2021-08-30 at 11 49 00

**Comment by sindrenm** [comment]
Looks nice! And very … Material. Is it worth bringing up if this is one of the places where perhaps Android and iOS may differ? If I'm not mistaken, many of the places we use these might be better off with segmented controls?

**Comment by fespinoza** [comment]
> Looks nice! And very … Material. Is it worth bringing up if this is one of the places where perhaps Android and iOS may differ? If I'm not mistaken, many of the places we use these might be better off with segmented controls?

Possibly, this is a legacy thing in terms of design for iOS. The main reason I re-created it is that I'm reimplementing the followers/followees list without changing the design/current behavior. In any case I think you have a good point

**Comment by fespinoza** [comment]
@kentrh there was just a white color I had in there in the demo, but nice catch anyway!

**Pull request merged**
