### PR TITLE
Improvement: allow to "retry" on error notices

### PR DESCRIPTION
**Pull request by fespinoza**
When errors occur and we use notice, we may want to add a retry button to the error case of notices

This will be used in the new friend's profile

Screenshot 2021-11-23 at 09 44 39

If an error has the `onRetry` parameters it won't autoDismiss.

### CODE REVIEW

**Review by kentrh — APPROVED** [review]
Nice! Good job! 

Are design and android kept in the loop on this?

**Review by SatseAndrew — APPROVED** [review]
Nice feature 👍

**Comment by sindrenm** [comment]
> Are design and android kept in the loop on this?

Pfft, give me a break, we don't even have the fancy snack bar to begin with! :sunglasses:

**Comment by fespinoza** [comment]
> Are design and android kept in the loop on this?

I did talk with Magnus about it and also commented about it to @sindrenm, but he is very aware with everything iOS related of course

**Pull request merged**
