### PR TITLE
Internal: create PR template

### PR DESCRIPTION
**Pull request by fespinoza**
Based on https://github.com/finn-no/FinniversKit/blob/master/PULL_REQUEST_TEMPLATE.md and our discussions in the iOS team

Add an initial version of the PR template.

The idea when doing a PR is to remove sections that don't apply and fill what it makes sense.

Since this is a team effort, I expect all iOS devs in the team to review/approve this PR.

Please comment if you think anything is missing or if you have suggestions

### CODE REVIEW

**Review by SatseAndrew — APPROVED** [review]
Very nice! 👍

**Comment by SvenAndreSvensson** [comment]
design: https://www.figma.com/file/QnfM8Y8LumG22KKiGhWS1g/03-Home?node-id=420%3A1616
Bff:  https://test-hfnapi.sats.com/sats-mobileapp-bff/swagger/ui#/eventlog/GetEventLogOverview

# Why
_A short description on what's the reasoning was behind these changes._

# What
_A summary of what has changed and if there's anything in special that you would like feedback on._

||||
|:---:|---:|:---|
| ✅ | unit tests | testModuleFollowers, testModuleFollowing |
| ☑️ | snapshot tests | no relevant visual changes |
| ☑️ | feature flag | new_event_log, all ready implemented |
| ⚠️ | version | breaking change, - we need to ... |
| ✅ | version | minor |

❌,  ✅, ☑️ not needed, ⚠️ warning

# Demo
followers

# UI Changes
_If the change concerns UI, a transition or an animation, providing an image, a gif, or a video is encouraged to help us reviewing your PR._
| Before | After |
| --- | --- |
| _Before image/gif_ | _After image/gif_ |

_Alternatively_

| | Feature A | Feature B |
| --- | --- | --- |
| **iPhone** | _Some image/gif_ | _Some image/gif_ |
| **iPad** | _Some image/gif_ | _Some image/gif_ |

**Comment by SvenAndreSvensson** [comment]
# So the template proposal is:
design: _link to Figma or what not_
Bff: _link to swagger or?_

# Why
_A short description on what's the reasoning was behind these changes._

# What
_A summary of what has changed and if there's anything in special that you would like feedback on._

<br>

||||
|:---:|---:|:---|
| ❌ | unit tests | not implemented |
| ❌ | snapshot tests | not implemented |
| ❌ | feature flag | not implemented |
| ✅ | version | minor |

❌,  ✅, ☑️ not needed, ⚠️ warning

# Demo

# UI Changes
_If the change concerns UI, a transition or an animation, providing an image, a gif, or a video is encouraged to help us reviewing your PR._
| Before | After |
| --- | --- |
| _Before image/gif_ | _After image/gif_ |

_Alternatively_

| | Feature A | Feature B |
| --- | --- | --- |
| **iPhone** | _Some image/gif_ | _Some image/gif_ |
| **iPad** | _Some image/gif_ | _Some image/gif_ |

**Review by SvenAndreSvensson — APPROVED** [review]
Good work 👍

**Review by PetterSW — APPROVED** [review]
👍🏼 Very nice!

**Pull request merged**
